#!/bin/sh
# Iterm2 Preferences Setup
set -x

# symlink settings in
iterm_prefs=~/Library/Preferences/com.googlecode.iterm2.plist
mv "$iterm_prefs" "$iterm_prefs.backup"
ln -s "$ZSH/iterm2/com.googlecode.iterm2.plist" "$iterm_prefs"