#!/bin/sh
# Iterm2 Preferences Setup

# copy iterm prefs and colors
cp ~/.dotfiles/iterm2/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist
cp ~/.dotfiles/iterm2/com.googlecode.iterm2.itermcolors ~/Library/Preferences/com.googlecode.iterm2.itermcolors
